openapi: 3.0.0
info:
  title: 10-Hotels-Reservia
  contact: {}
  version: '1.0'
servers:
- url: https://bouba-hotel-reservia.herokuapp.com/api/v1
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - auth
      summary: register user
      operationId: registeruser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registeruserrequest'
            example:
              name: abou
              lastName: ama
              email: abou@gmail.com
              password: '12345678'
              role: admin
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - auth
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginrequest'
            example:
              email: bouba1@gmail.com
              password: '12345678'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /hotels:
    post:
      tags:
      - Hotels
      summary: create Hotel
      operationId: createHotel
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createHotelRequest'
            example:
              name: hayat
              price: 450
              location: France
              description: Sun Riviera is located in central Cannes, a few minutes’ walk from Boulevard de la Croisette. It offers an outdoor terrace and a Mediterranean garden. The train station is a 10-minute walk awa
              averageRating: 4
              image: /uploads/pexels-cottonbro-4629624.jpg
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    get:
      tags:
      - Hotels
      summary: get all hotels
      operationId: getallhotels
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /hotels/uploadImage:
    post:
      tags:
      - Hotels
      summary: uploadImage
      operationId: uploadImage
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - image
              type: object
              properties:
                image:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /hotels/stats:
    get:
      tags:
      - Hotels
      summary: show stats
      operationId: showstats
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /hotels/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    get:
      tags:
      - Hotels
      summary: get single Hotel
      operationId: getsingleHotel
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  
    patch:
      tags:
      - Hotels
      summary: Update hotel
      operationId: Updatehotel
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatehotelRequest'
            example:
              name: Hayat
              price: 600
              location: France
              description: Situated in Cannes, 1.1 km from Plage de la Croisette and 1.1 km from Plage du Palais des Festivals, Cannes Downtown offers free WiFi, a casino and air conditioning.
              averageRating: 4
              image: /uploads/image1.jpg
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  
    delete:
      tags:
      - Hotels
      summary: delete hotel
      operationId: deletehotel
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /users:
    get:
      tags:
      - User
      summary: getAllUsers
      operationId: getAllUsers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    get:
      tags:
      - User
      summary: get a singleUser
      operationId: getasingleUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /users/showMe:
    get:
      tags:
      - User
      summary: ShowMe
      operationId: ShowMe
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /users/updateUser:
    patch:
      tags:
      - User
      summary: update User
      operationId: updateUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUserRequest'
            example:
              name: lil
              lastName: amam
              email: lilama@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /users/updateUserPassword:
    patch:
      tags:
      - User
      summary: update UserPassword
      operationId: updateUserPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUserPasswordRequest'
            example:
              oldPassword: '12345678'
              newPassword: Lilama
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
components:
  schemas:
    registeruserrequest:
      title: registeruserrequest
      required:
      - name
      - lastName
      - email
      - password
      - role
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
      example:
        name: abou
        lastName: ama
        email: abou@gmail.com
        password: '12345678'
        role: admin
    loginrequest:
      title: loginrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: bouba1@gmail.com
        password: '12345678'
    createHotelRequest:
      title: createHotelRequest
      required:
      - name
      - price
      - location
      - description
      - averageRating
      - image
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        location:
          type: string
        description:
          type: string
        averageRating:
          type: integer
          format: int32
        image:
          type: string
      example:
        name: hayat
        price: 450
        location: France
        description: Sun Riviera is located in central Cannes, a few minutes’ walk from Boulevard de la Croisette. It offers an outdoor terrace and a Mediterranean garden. The train station is a 10-minute walk awa
        averageRating: 4
        image: /uploads/pexels-cottonbro-4629624.jpg
    UpdatehotelRequest:
      title: UpdatehotelRequest
      required:
      - name
      - price
      - location
      - description
      - averageRating
      - image
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        location:
          type: string
        description:
          type: string
        averageRating:
          type: integer
          format: int32
        image:
          type: string
      example:
        name: Hayat
        price: 600
        location: France
        description: Situated in Cannes, 1.1 km from Plage de la Croisette and 1.1 km from Plage du Palais des Festivals, Cannes Downtown offers free WiFi, a casino and air conditioning.
        averageRating: 4
        image: /uploads/image1.jpg
    updateUserRequest:
      title: updateUserRequest
      required:
      - name
      - lastName
      - email
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        email:
          type: string
      example:
        name: lil
        lastName: amam
        email: lilama@gmail.com
    updateUserPasswordRequest:
      title: updateUserPasswordRequest
      required:
      - oldPassword
      - newPassword
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      example:
        oldPassword: '12345678'
        newPassword: Lilama
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: auth
- name: Hotels
- name: User